spring: 
  application:
    name: AR-API  
  config:
    import: optional:configserver:http://localhost:9999
server:
  port: 9094

ssaWebApiURL: http://localhost:9091/get/{ssn}
logging:
  file:
    name: ApplicationAPI.log